# Generated by Django 4.0.5 on 2022-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=25, unique=True)),
                ('name_of_author', models.CharField(max_length=25)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
